/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import DAO.CourseDAO;
import DAOImp.CourseDAOImp;
import dbConnection.DBConnection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import dbConnection.DBConnection;
import java.sql.Connection;
import java.util.List;
import model.Course;
import DAO.DepartmentDAO;
import DAOImp.DepartmentDAOImp;
import DAOImp.StudentDAOImp;

import dbConnection.DBConnection;
import java.sql.Connection;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Department;

/**
 *
 * @author SAQIB
 */
public class CourseFrame extends javax.swing.JFrame {
Integer courseId;
CourseDAO courseDAO = new CourseDAOImp();
     Object columns[]={"ID","Name","Code"};
    DefaultTableModel defaultTableModel;
    CourseDAO crsDAO=new CourseDAOImp();
    /**

    /**
     * Creates new form CourseFrame
     */
    public CourseFrame() {
        initComponents();
                defaultTableModel=(DefaultTableModel) bTable.getModel();
                fillCourseTable();
                setLocationRelativeTo(null);

    }
    private boolean validateFields() {
        if (bName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(CourseFrame.this, "Enter any Name");
            bName.grabFocus();
            return false;
        }
        if (bCode.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(CourseFrame.this, "Enter any Code");
            bCode.grabFocus();
            return false;
        }
        
   
        return true;
    }

    private void resetFields() {
       bName.setText("");
       bCode.setText("");
 
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bName = new javax.swing.JTextField();
        bCode = new javax.swing.JTextField();
        bInsert = new javax.swing.JButton();
        bUpdate = new javax.swing.JButton();
        bClear = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("Course");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\SAQIB\\Downloads\\arrow.png")); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(257, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 663, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 108, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Code");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 108, 37, -1));
        getContentPane().add(bName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 108, 185, -1));
        getContentPane().add(bCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 108, 178, -1));

        bInsert.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bInsert.setText("Insert");
        bInsert.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 153)));
        bInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInsertActionPerformed(evt);
            }
        });
        getContentPane().add(bInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 170, 36));

        bUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bUpdate.setText("Update");
        bUpdate.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 153)));
        bUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(bUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 170, 36));

        bClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bClear.setText("Clear");
        bClear.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 153)));
        bClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClearActionPerformed(evt);
            }
        });
        getContentPane().add(bClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 170, 36));

        bDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bDelete.setText("Delete");
        bDelete.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 153)));
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(bDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 170, 36));

        bTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Code"
            }
        ));
        bTable.getTableHeader().setReorderingAllowed(false);
        bTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 330, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUpdateActionPerformed
        Course course = this.getCourse();
        course.setCrs_ID(courseId);
        boolean success = courseDAO.updateCourse(course);
        if (success) {
            JOptionPane.showMessageDialog(this, "Updated Successfully");
            fillCourseTable();
            resetFields();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_bUpdateActionPerformed

    private void bInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInsertActionPerformed
      
                Connection con = DBConnection.getConnection();// TODO add your handling code here:

        CourseDAO depdao = new CourseDAOImp();
        Course crs = new Course();
        crs.setCrs_name(bName.getText());
        crs.setCrs_code(bCode.getText());

        //    ps.setString(6, bDepartment.getSelectedItem().toString());
        
        JOptionPane.showMessageDialog(this, "Success");
        boolean success = depdao.addCourse(crs);
        if(success){
            JOptionPane.showMessageDialog(this,"added successfully");
             fillCourseTable();
            
        }
     
    }//GEN-LAST:event_bInsertActionPerformed
	
    private void bClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClearActionPerformed
        resetFields();
    }//GEN-LAST:event_bClearActionPerformed
    private Course getCourse() {
        String name = bName.getText();
        String code = bCode.getText();
        Course c = new Course();
        c.setCrs_name(name);
        c.setCrs_code(code);
        return c;
    }
    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        
        
            Course course = this.getCourse();
        course.setCrs_ID(courseId);
        boolean success = courseDAO.deleteCourse(courseId);
        if (success) {
            JOptionPane.showMessageDialog(this, "Deleted Successfully");
            fillCourseTable();

            resetFields();
    }//GEN-LAST:event_bDeleteActionPerformed
    }
    private void bTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bTableMouseClicked
        // TODO add your handling code here:
          courseId = Integer.valueOf(bTable.getValueAt(bTable.getSelectedRow(), 0).toString());
        Course course = courseDAO.getCourseById(courseId);
        bName.setText(course.getCrs_name());
        bCode.setText(course.getCrs_code());
    }//GEN-LAST:event_bTableMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
       Selection  selection =new  Selection();
       CourseFrame.this.setVisible(false);
        selection.setVisible(true);
        CourseFrame.this.dispose();
           
    }//GEN-LAST:event_jLabel4MouseClicked
 
//      private void fillTable(){
//                defaultTableModel = new DefaultTableModel(columns, 0);
//                        List<Course> prod = crsDAO.getAllCourse();
//               for(Course c: prod){
//                Object[] row={c.getCrs_ID(),c.getCrs_name(),c.getCrs_code()};
//                defaultTableModel.addRow(row);
//                bTable.setModel(defaultTableModel);
//                        }
//   
    
    
     private void fillCourseTable() {
        defaultTableModel = new DefaultTableModel(columns, 0);
        List<Course> course = courseDAO.getAllCourse();

        for (Course c : course) {
            Object[] row = {c.getCrs_ID(), c.getCrs_name(), c.getCrs_code()};
            defaultTableModel.addRow(row);
            bTable.setModel(defaultTableModel);
        }
        bTable.getColumnModel().getColumn(0).setWidth(0);
        bTable.getColumnModel().getColumn(0).setMinWidth(0);
        bTable.getColumnModel().getColumn(0).setMaxWidth(0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CourseFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClear;
    private javax.swing.JTextField bCode;
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bInsert;
    private javax.swing.JTextField bName;
    private javax.swing.JTable bTable;
    private javax.swing.JButton bUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
